[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "16"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3003
  targetPort = 3003

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 